import Head from "next/head";
import { useRouter } from "next/router";

import CompanyPage from "../../app/components/templates/CompanyPage";
import { NextPageWithLayout } from "../../app/types/next-page";

const Company: NextPageWithLayout = () => {
  const router = useRouter();
  const { _id } = router.query as Record<string, string>;

  return (
    <div>
      <Head>
        <title>Company - Prometheus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <CompanyPage _id={_id} />
    </div>
  );
};

Company.layout = "main";
Company.middleware = "auth";

export default Company;
