import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";

import CompanyPage from "../../app/components/templates/CompanyPage";
import { NextPageWithLayout } from "../../app/types/next-page";
import { useCompany } from "mobile/src/graphql/query/company/useCompany";
import { useProfile } from "mobile/src/graphql/query/user/useProfile";

const Company: NextPageWithLayout = () => {
  const router = useRouter();
  const { data: session } = useSession();
  const { companyId } = router.query as Record<string, string>;
  const { data: companyData } = useCompany(companyId);
  const { data: profileData } = useProfile(session!.user!._id);
  const company = companyData?.companyProfile;
  const user = profileData?.userProfile;
  const isMyCompany: number =
    user?.companies.findIndex((v) => v._id === companyId) ?? -1;

  return (
    <div>
      <Head>
        <title>{company ? company.name : "Company"} - Prometheus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {company && (
        <CompanyPage
          company={company}
          isEditable={isMyCompany > -1 ? true : false}
        />
      )}
    </div>
  );
};

Company.layout = "main";
Company.middleware = "auth";

export default Company;
