import Head from "next/head";
import CompaniesPage from "../app/frontend/components/templates/CompaniesPage";
import { NextPageWithLayout } from "../app/types/next-page";

const Companies: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Companies - Prometheus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CompaniesPage />
    </div>
  );
};

Companies.layout = "main";
Companies.middleware = "auth";

export default Companies;
