import Head from "next/head";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";

import { useProfile } from "mobile/src/graphql/query/user/useProfile";
import ProfilePage from "../../app/components/templates/ProfilePage";
import { NextPageWithLayout } from "../../app/types/next-page";

const Profile: NextPageWithLayout = () => {
  const router = useRouter();
  const { data: session } = useSession();
  if (!session) return null;

  const { userId } = router.query as Record<string, string>;
  const { data: profileData } = useProfile(
    userId === "me" || userId === "edit" ? session.user!._id : userId
  );

  const user = profileData?.userProfile;
  const title =
    userId === "me" || userId === "edit"
      ? "My Profile - Prometheus"
      : `${
          user ? `${user.firstName} ${user.lastName}` : "Profile"
        } - Prometheus`;

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user && <ProfilePage user={user} isEditable={userId === "edit"} />}
    </div>
  );
};

Profile.layout = "main";
Profile.middleware = "auth";

export default Profile;
