import Head from "next/head";
import ProfilePage from "../../app/components/templates/ProfilePage";
import { NextPageWithLayout } from "../../app/types/next-page";
import { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import { useProfile } from "mobile/src/graphql/query/user/useProfile";

const Profile: NextPageWithLayout = () => {
  const router = useRouter();
  const { data: session } = useSession();
  if (!session) return null;

  let { userId } = router.query as Record<string, string>;
  if (userId === "me") {
    userId = session.user!._id;
  }

  const { data: profileData } = useProfile(userId);
  const user = profileData?.userProfile;
  const title =
    userId == "me"
      ? "My Profile - Prometheus"
      : `${
          user ? `${user.firstName} ${user.lastName}` : "Profile"
        } - Prometheus`;

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user && <ProfilePage user={user} />}
    </div>
  );
};

Profile.layout = "main";
Profile.middleware = "auth";

export default Profile;
