import Head from "next/head";
import CompanyPage from "../app/components/templates/CompanyPage";
import { NextPageWithLayout } from "../app/types/next-page";

const Company: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Company - Prometheus</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CompanyPage />
    </div>
  );
};

Company.layout = "main";
Company.middleware = "guest";

export default Company;
