import Head from "next/head";

import SettingPage from "../app/components/templates/SettingPage";
import { NextPageWithLayout } from "../app/types/next-page";

const Home: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Home - Setting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SettingPage />
    </div>
  );
};

Home.layout = "main";
Home.middleware = "auth";

export default Home;
