import Head from "next/head";
import WelcomePage from "../app/components/templates/WelcomePage";
import { NextPageWithLayout } from "../app/types/next-page";

const Welcome: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Welcome - Prometheus</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <WelcomePage />
    </div>
  );
};

Welcome.layout = "onboarding";
Welcome.middleware = "guest";
Welcome.background = "radial";

export default Welcome;
